plugins { id 'com.android.application' }

android {
    namespace 'com.example.antilag'
    compileSdk 34
    defaultConfig { 
        applicationId "com.example.antilag"
        minSdk 24
        targetSdk 34
    }
    // Dòng này giúp Gradle hiểu file .so nằm ngay ở thư mục gốc
    sourceSets {
        main {
            jniLibs.srcDirs = ['.']
        }
    }
}
